version: '3.9'

services:
  car-price-prediction:
    image: lovelyprince/ait-ml-fastapi:2025_a3_1.0
    command: python3 main.py
    ports:
      - "8181:80"
    platform: linux/x86_64
    environment:
      - HOST=0.0.0.0
      - PORT=80
    labels:
      - traefik.enable=true
      - traefik.http.routers.car-price-prediction-st124876.rule=Host(`st124876.ml.brain.cs.ait.ac.th`)
      - traefik.http.routers.car-price-prediction-st124876.entrypoints=websecure
      - traefik.http.routers.car-price-prediction-st124876.tls=true
      - traefik.http.routers.car-price-prediction-st124876.tls.certresolver=production
      - traefik.http.routers.car-price-prediction-st124876.service=car-price-service
      - traefik.http.services.car-price-service.loadbalancer.server.port=80
    networks:
      - default
      - traefik_default

networks:
  default:
  traefik_default:
    external: true
