channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=25.0
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.0.0
  - lz4==4.3.2
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==5.9.6
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
