name: Build Test

run-name: ${{ github.actor }} Building and Testing

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    paths:
    - '**'
    # tags:
    #   - 'v*'

jobs:
  # Job name
  build-test:
    runs-on: ubuntu-latest
    # Tasks, specify in list.
    steps:
         # https://github.com/actions/checkout: will clone Git into the image
      - uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          file_name: .env
          fail_on_empty: true
          sort_keys: true
        env:
          MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
          APP_MODEL_NAME: ${{ secrets.APP_MODEL_NAME }}

      - name: Remove existing traefik_default network if exists
        run: docker network rm traefik_default || true
        
      - name: Create Docker Network
        run: docker network create traefik_default || true

      - name: Build the Docker image
        run: docker compose -f docker-compose.yaml build

      # 🆕 Add this to confirm network exists
      - name: List Docker networks
        run: docker network ls

      - name: Compose up
        # run: docker compose -f docker-compose.yaml up -d
        env:
          APP_MODEL_NAME: ${{ secrets.APP_MODEL_NAME }}
        run: docker compose -f docker-compose.yaml up -d

      - name: Wait for container
        run: sleep 10

      - name: Run tests in container
        run: docker compose exec car-price-prediction bash -c "PYTHONPATH=. python3 -m pytest tests/test_model_staging.py -v"
        # run: docker compose -f docker-compose.yaml run --rm car-price-prediction pytest tests/test_app_callbacks_v2.py -v
        # If test successfully, deploy it to dockerhub

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: LovelyPrince/ait-ml-fastapi
          # tag-separator: "-"
          # tags: |
          #   type=schedule
          #   type=ref,event=branch
          #   type=ref,event=pr
          #   type=semver,pattern={{version}}
          #   type=semver,pattern={{major}}.{{minor}}
          #   type=semver,pattern={{major}}
          #   type=semver,pattern=latest
          #   type=sha
          tags: type-semver, pattern={{raw}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  # deploy:
  #     environment: Production
  #     needs: build-test
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: SSH Remote Commands
  #         uses: appleboy/ssh-action@v1.0.0
  #         with:
  #           host: ml2025
  #           # port: 2222
  #           username: st124876
  #           key: ${{ secrets.SSH_PRIVATE_KEY }}
  #           passphrase: ${{ secrets.SSH_PASSPHRASE }}
  #           proxy_host: bazooka.cs.ait.ac.th
  #           # proxy_port: 2222
  #           proxy_username: st124876
  #           proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
  #           proxy_passphrase: ${{ secrets.SSH_PASSPHRASE }}
  #           script: |
  #             docker compose -f docker-compose.yaml down
  #             docker image rm lovelyprince/ait-ml-fastapi:2025_a3_1.0 --force
  #             docker compose -f docker-compose.yaml up -d

              
  deploy:
    environment: Production
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key and config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/st124876
          chmod 600 ~/.ssh/st124876

          cat << 'EOF' > ~/.ssh/config
          Host bazooka
            HostName bazooka.cs.ait.ac.th
            User st124876
            IdentityFile ~/.ssh/st124876

          Host ml2025
            HostName ml.brain.cs.ait.ac.th
            User st124876
            IdentityFile ~/.ssh/st124876
            ProxyJump bazooka
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOF
          chmod 600 ~/.ssh/config

          # add bazooka to known hosts...
          ssh-keyscan -p 22 -H bazooka.cs.ait.ac.th >> ~/.ssh/known_hosts 2>/dev/null || echo "Warning: Failed to scan bazooka host key"
          chmod 600 ~/.ssh/known_hosts

      - name: SSH Remote Deployment
        run: |
          ssh ml2025 << 'EOF'
          docker compose -f docker-compose.yaml down || true
          docker image rm lovelyprince/ait-ml-fastapi:2025_a3_1.0 --force || true
          docker network create traefik_default || true
          docker compose -f docker-compose.yaml up -d
          EOF