# Name of this workflow
name: Test Model on Staging
# Name of this run
run-name: ${{ github.actor }} Test model on staging

# there is no trigger. I will do it manaully in GitHub.
on: workflow_dispatch

jobs:
  staging-test:
    runs-on: ubuntu-latest
    steps:
      # This is the same as build-test
      - uses: actions/checkout@v4
      # We won't build
      # - name: Build the Docker image
      #   run: docker compose build
      # This will only load the latest image
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          file_name: .env
          fail_on_empty: true
          sort_keys: true
        env:
          MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
          APP_MODEL_NAME: ${{ secrets.APP_MODEL_NAME }}
          
      - name: Compose up
        run: |
          docker network create traefik_default || true
          docker compose up -d

      # Debu
      - name: Show container files
        run: docker compose exec car-price-prediction ls -R /root/code || true
      - name: Show FastAPI crash logs
        run: docker compose logs car-price-prediction || true
      - name: Try to run bash in container to explore
        run: docker compose exec car-price-prediction bash -c "ls -l /root/code && cat /root/code/app/main.py" || true
      # - name: Check if pytest exists
      #   run: docker compose exec car-price-prediction which pytest
      
      
      # This is new
      # only run test on test_model_staging.py
      - name: Testing
        run: docker compose exec -it car-price-prediction python3 pytest tests/test_model_staging.py
        # run: docker compose exec car-price-prediction bash -c "PYTHONPATH=. python3 -m pytest tests/test_model_staging.py -v"
        # run: docker compose exec car-price-prediction bash -c "PYTHONPATH=. python3 -m pytest tests/test_app_callbacks_v2.py -v"
      - name: Transition to production
        run: docker compose exec -it car-price-prediction python3 -m /root/transition.py